DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS EMPLOYEE;


CREATE TABLE DEPARTMENT (
       ID INT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(60) NOT NULL
     , UNIQUE UQ_DEPARTMENT_1 (NAME)
     , PRIMARY KEY (ID)
    
);


CREATE TABLE EMPLOYEE (
	   ID INT NOT NULL AUTO_INCREMENT
	 , DEPARTMENT_ID INT NOT NULL
     , NAME VARCHAR(60) NOT NULL
	 , UNIQUE UQ_EMPLOYEE_1 (NAME)
     , PRIMARY KEY (ID)
	 , CONSTRAINT FK_EMPLOYEE_1 FOREIGN KEY (DEPARTMENT_ID)
	   REFERENCES DEPARTMENT (ID)
);


